version: 1.0.{build}-{branch}

environment:
  BOOST_HOME: C:/Libraries/boost_1_66_0
  PATH: C:\Ruby25-x64\bin;$(PATH);C:\cygwin64\bin

platform: x64

cache:
  - ThirdParty

install:
  - ps: gem install os colorize rubyzip json sha3

build_script:
  - ps: ruby Setup.rb --precompiled

test_script:
  - ps: cd build\bin
  - ps: .\LeviathanTest ~[xrequired]
