version: 1.0.{build}-{branch}

environment:
  BOOST_ROOT: C:/Libraries/boost_1_66_0
  PATH: C:\Ruby25-x64\bin;$(PATH);C:\cygwin64\bin
  VULKAN_SDK: C:/VulkanSDK/1.1.114.0

image:
  - Visual Studio 2017

platform: x64

init:
  - curl -L --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.114.0/windows/VulkanSDK-1.1.114.0-Installer.exe?Human=true
  - VulkanSDK.exe /S
  - rm -f VulkanSDK.exe

cache:
  - ThirdParty
  - bin

install:
  - gem install os colorize rubyzip json sha3

build_script:
  - ruby Setup.rb --precompiled

test_script:
  - cd build\bin
  - .\LeviathanTest ~[xrequired]
