version: 2
jobs:
   build:
     working_directory: ~/leviathan
     docker:
       - image: hhyyrylainen/leviathan-deps:latest
     steps:
       - checkout
       - run: ./Setup.rb --no-packagemanager
