version: 2
jobs:
   build:
     working_directory: ~/leviathan
     docker:
       - image: hhyyrylainen/leviathan-deps:latest
     steps:
       - checkout
       - restore_cache:
           keys:
             - v1-deps-{{ checksum "Setup.rb" }}
             - v1-deps
       - restore_cache:
           keys:
             - v1-assets-{{ .Branch }}
             - v1-assets
       - restore_cache:
           keys:
             - v2-build-{{ .Branch }}
       - run: ./Setup.rb --no-packagemanager --no-updates -j 1 --fully-parallel-project-compile --project-parallel 5
       - save_cache:
           key: v1-assets-{{ .Branch }}
           paths:
             - bin/Data
       - save_cache:
           key: v1-assets
           paths:
             - bin/Data
       - save_cache:
           key: v1-deps-{{ checksum "Setup.rb" }}
           paths:
             - ThirdParty
       - save_cache:
           key: v1-deps
           paths:
             - ThirdParty
       - save_cache:
           key: v2-build-{{ .Branch }}
           paths:
             - build/Engine
             - build/LeviathanTest
             - build/Pong
             - build/PongMasterServer
             - build/PongServer
             - build/CMakeFiles
             - build/CMakeCache.txt
             - build/Makefile
       - run: mkdir -p /reports/reports
       - run:
           command: ./LeviathanTest --reporter junit --out /reports/reports/test_run.xml "~[xrequired]"
           working_directory: ~/leviathan/build/bin
       - store_test_results:
           path: /reports/reports
