version: 2
jobs:
   build:
     working_directory: ~/leviathan
     docker:
       - image: fedora:latest
     steps:
       - checkout
       - run: ruby gem install os colorize rubyzip
       - run: ./Setup.rb --no-packagemanager
