version: 2
jobs:
   build:
     working_directory: ~/leviathan
     docker:
       - image: hhyyrylainen/leviathan-deps:latest
     steps:
       - checkout
       - restore_cache:
           keys:
             - v4-deps-{{ arch }}-{{ checksum "Setup.rb" }}-{{ checksum "LeviathanLibraries.rb" }}
             - v4-deps-{{ arch }}
       - restore_cache:
           keys:
             - v4-assets-{{ .Branch }}
             - v4-assets
       - restore_cache:
           keys:
             - v3-build-{{ arch }}-{{ .Branch }}
       - run: ./Setup.rb --no-packagemanager --no-updates -j 2 --fully-parallel-project-compile --project-parallel 5
       - save_cache:
           key: v4-assets-{{ .Branch }}
           paths:
             - bin
       - save_cache:
           key: v4-assets
           paths:
             - bin
       - save_cache:
           key: v4-deps-{{ arch }}-{{ checksum "Setup.rb" }}-{{ checksum "LeviathanLibraries.rb" }}
           paths:
             - ThirdParty
       - save_cache:
           key: v4-deps-{{ arch }}
           paths:
             - ThirdParty
       - save_cache:
           key: v3-build-{{ arch }}-{{ .Branch }}
           paths:
             - build/Engine
             - build/LeviathanTest
             - build/Pong
             - build/PongMasterServer
             - build/PongServer
             - build/CMakeFiles
             - build/CMakeCache.txt
             - build/Makefile
       - run: mkdir -p /reports/reports
       - run:
           command: ./LeviathanTest "~[xrequired]"
           working_directory: ~/leviathan/build/bin
       # - run:
       #     command: ./LeviathanTest --reporter junit --out /reports/reports/test_run.xml "~[xrequired]"
       #     working_directory: ~/leviathan/build/bin
       # - store_test_results:
       #     path: /reports/reports
